### ISSUE TITLE
cannot open readme pdf link

### ISSUE THREAD

**Issue by hackershi** [wzhe06/Reco-papers#1]
404 error

**Comment by chandlervan** [comment]
me neither.

**Comment by wzhe06** [comment]
What do you mean by readme pdf link? Could you send me the link?

**Comment by hackershi** [comment]
> What do you mean by readme pdf link? Could you send me the link?

for example, the link of Item2Vec - Neural Item Embedding for Collaborative Filtering.pdf 
,which is 
https://github.com/wzhe06/Ad-papers/blob/master/Recommendation/Item2Vec%20-%20Neural%20Item%20Embedding%20for%20Collaborative%20Filtering.pdf.
open this link only gets 404 error

**Comment by wzhe06** [comment]
@hackershi Thanks for your feedback. I have fixed the bug in readme file generator. All links are available now, enjoy it. thanks.
